[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "truchet-tiling"
version = "0.1.0"
requires-python = ">= 3.8"
dependencies = [
  "pygame",
]

[tool.hatch.build.targets.wheel]
packages = ["src/truchet_tiles"]
